module.exports = [
  ['var', /^var/],
  ['null', /^null/],
  ['bool', /^(true|false)/],
  ['string', /^"[^"]*"/],
  ['num', /^\d*\.?\d+/],
  ['if', /^if/],
  ['else', /^else/],
  ['while', /^while/],
  ['print', /^print/],
  ['comp_op', /^(>=|<=|==|!=|>|<)/],
  ['mat_op', /^(\+|-|\*|\/|%)/],
  ['log_op', /^(or|and)/],
  ['id', /^[_a-zA-Z]\w*/],
  ['=', /^=/],
  ['(', /^\(/],
  [')', /^\)/],
  ['{', /^{/],
  ['}', /^}/],
  [';', /^;/],
];
